### ISSUE TITLE
Camera wiki update

### ISSUE THREAD

**Issue by 4aiman** [groverburger/g3d#13]
Hey there ;)

The page about camera aspect ratio needs an update sine gd3 is now modular (to something like this):
```
g3d.camera.aspectRatio = love.graphics.getWidth()/love.graphics.getHeight()
g3d.camera.updateProjectionMatrix()
```

**Comment by groverburger** [comment]
done :)

**Comment by TangentFoxy** [comment]
Either this got reverted somehow or the same update is missing on https://github.com/groverburger/g3d/wiki/Everything-is-stretched-when-I-change-the-window-size
