### ISSUE TITLE
custom vertex format help

### ISSUE THREAD

**Issue by giovifav** [groverburger/g3d#14]
hello, 
i need some help to create a new model from vertices
i'm making a map generator based on perlin noise and i want to create a custom  model/mesh for ground. the generator return a table with a list of 3d point like {x, height, y}.
i have tried to feed the function g3d.newModel with that table and a texture  but seem no working correctly.
there is a right way that i'm ignore?
sorry if the question seem silly, i'm a noob!
thanks!

![Screenshot from 2021-05-31 18-49-29](https://user-images.githubusercontent.com/6899005/120223107-59315480-c241-11eb-92ca-de3604e25e76.png)

edit:
I just dig into the source and i just realize the use of love mesh. Now my question seem more odd.
So, for every vertex i need to build a table like this { x, y, z, texturex, texturey, normalx, normaly, normalz} ?
edit2:
still have problems i think i'm using the wrong normal vector :(
![Immagine](https://user-images.githubusercontent.com/6899005/120305690-5aaa5d80-c2d1-11eb-8d96-2255517ade2e.png)

**Comment by groverburger** [comment]
This does not appear to be a problem with g3d itself, so I'm closing this issue.

From the bit of code you showed, you seem to be adding one point to the mesh for each x, z coordinate. However, you must understand that meshes are created from triangles and your mesh must be built with that in mind. It does not seem like you need a custom vertex format for what you want, as that refers to a different concept. I hope that helps! If you want more help, try asking this question on the [love2d forums](https://love2d.org/forums/).
