### ISSUE TITLE
Normal not getting setted

### ISSUE THREAD

**Issue by Lifistic** [groverburger/g3d#19]
Hi,

I'm creating a model which is basically a plane like this: 
`local tile = g3d.newModel({
	{-3, 0, 2, 0, 0},
	{ 2, 0, 2, 1, 0}, 
	{ 2, 0,-1.5, 1, 1},
	{-3, 0, 2, 0, 0},
	{ 2, 0,-1.5, 1, 1}, 
	{-3, 0,-1.5, 0, 1},
})`

I want it to be visible only from one side so i decided to try:
`tile:makeNormals()`
before drawing the mesh.

Problem is that the mesh still draws white on both side.

Is the problem coming from a misuse or a bug?

Thank you

**Comment by EngineerSmith** [comment]
Normals have nothing to do with front face culling, that's a function within  `love.graphics` use [love.graphics.setMeshCullMode](https://love2d.org/wiki/love.graphics.setMeshCullMode) and [love.graphics.setFrontFaceWinding](https://love2d.org/wiki/love.graphics.setFrontFaceWinding) to cull your meshes faces

**Comment by Lifistic** [comment]
Problem solved, thank you
