### ISSUE TITLE
Wrong texture coordinates with OBJ

### ISSUE THREAD

**Issue by ddabrahim** [groverburger/g3d#22]
Hi.

I'm trying to load an OBJ model using g3d but for some reason it does not apply the textures properly.
I have tested and the model does work fine with other engines.

This is how it supposed to look:
<img width="1050" alt="screenshot of correct rendering" src="https://user-images.githubusercontent.com/24738433/158079224-2c72bd0e-fb46-42c5-838a-c75165e75b41.png">

But this is what I get with g3d:
<img width="794" alt="screenshot of wrong textures" src="https://user-images.githubusercontent.com/24738433/158079330-6e5ea853-c558-4aaa-8871-2f74e59b057f.png">

Here is an example project:
[g3dtest.zip](https://github.com/groverburger/g3d/files/8240608/g3dtest.zip)

Love 11.4
g3d 1.5.1
macOS 12.2.1

Any idea what could be the problem and if there is any work around, solution?

I would appreciate any help. 
Thank you.

**Comment by EngineerSmith** [comment]
It works if you flip the texture vertically, which is weird as g3d doesn't change the pixel shader love uses, so it should just work. Could edit the obj loader to flip the textures vertically
Change line 32 to:
```lua
table.insert(uvs, {tonumber(words[2]), 1-tonumber(words[3])})
```

**Comment by ddabrahim** [comment]
Thanks a lot! Flipping the texture indeed worked.
