### ISSUE TITLE
Rendering problem with Canvas

### ISSUE THREAD

**Issue by ddabrahim** [groverburger/g3d#23]
Hi.

I'm trying to draw a 3D mesh on to a Canvas and then draw the canvas, however it seems it does not render properly.

This is the result I would like to achieve:
<img width="794" alt="without-canvas" src="https://user-images.githubusercontent.com/24738433/158888416-06b47c29-d429-4509-a9d5-f349f4f04c24.png">

But this is what I get if I draw on to a canvas:
<img width="794" alt="with-canvas" src="https://user-images.githubusercontent.com/24738433/158888494-c71235c3-cd82-4c28-9801-9c1e522e9e48.png">

Here is an example that reproduce the problem:
[g3dtest-canvas.zip](https://github.com/groverburger/g3d/files/8291365/g3dtest-canvas.zip)

Love 11.4
g3d 1.5.1
macOS 12.2.1

Not entirely certain if it's a bug, could someone please tell me why is this happening and if there is any possible work around, solution to this?

I would appreciate any help.

Thank you.

**Comment by groverburger** [comment]
You can also look in the Github wiki, this is listed under the FAQ section.

https://github.com/groverburger/g3d/wiki/Can%27t-render-models-to-canvas

**Comment by ddabrahim** [comment]
Thanks a lot it worked!  For some reason I was not aware of the wiki. In the future I am going to check the documentation before posting 👍
