### ISSUE TITLE
Please explain how the collision functions work more clearly on the wiki

### ISSUE THREAD

**Issue by drjellyjam** [groverburger/g3d#24]
This is really my only complaint for the Wiki, everything is pretty clear but I have no idea how the collisions work. I've tried my best guesses on how I would use it but I'm fairly new using g3d and it would be nice if it was a tiny bit clearer.

Thats all!

**Comment by Brooccooli** [comment]
Same, almost made it work but can't make it consistent

**Comment by groverburger** [comment]
I'm not set on even leaving the current collision functionality in g3d, as it's pretty half-baked. Closing this issue for now.
