### ISSUE TITLE
How can I make Exclusive Fullscreen work?

### ISSUE THREAD

**Issue by xeonmc** [groverburger/g3d#26]
editing conf.lua correctly sets exclusive fullscreen but the resolution has to be entered manually. I would like to programmatically detect the user's screen resolution, however every entrypoint that I tried placing `love.window.setMode` causes the assets to disappear entirely. I'm not sure what the right function call or placement I should be making the fullscreen toggle.

**Comment by groverburger** [comment]
I don't understand what could be causing this problem. Maybe it's because of the difference in aspect ratio between windowed and fullscreen?
