### ISSUE TITLE
Can this load .mtl files?

### ISSUE THREAD

**Issue by RealJace** [groverburger/g3d#35]
So I'm using a model which has a mtl file but it can't be loaded in g3d, so is it possible or png is the only supported format?

**Comment by groverburger** [comment]
The only filetype that g3d adds support for are obj files. I don't think Love has support for mtl files, in which case you're out of luck. There's nothing stopping you from writing a custom loader and a shader for it, though.

**Comment by RealJace** [comment]
Yeah I will try to add .mtl textures loading, still, thank's for answering.
