### ISSUE TITLE
Question about models

### ISSUE THREAD

**Issue by vico93** [groverburger/g3d#38]
Hello!

Just start playing around with g3d trying to make a simple voxel game, i have a question about models: do i need to load a .obj file or is possible to render basic shapes (like a cube) via pure code?

I have plans to create a text-based format for models (like Minecraft does using .json-like format) and i dont want to use .obj at all.

**Comment by groverburger** [comment]
Yes, you can create models using purely code.

You should check out my g3d_voxel demo (listed on the g3d Github page), which is a simple voxel world with procedural generation. This would not have been possible without creating models using code, and referencing its codebase might be helpful for you in designing your own. Here's the link: https://github.com/groverburger/g3d_voxel

**Comment by vico93** [comment]
> Yes, you can create models using purely code.
> 
> You should check out my g3d_voxel demo (listed on the g3d Github page), which is a simple voxel world with procedural generation. This would not have been possible without creating models using code, and referencing its codebase might be helpful for you in designing your own. Here's the link: https://github.com/groverburger/g3d_voxel

Thanks. I was looking through that code. Althrough i didnt recognize much things there (i'm not that familar with Lua yet) i noticed on [this file](https://github.com/groverburger/g3d_voxel/blob/master/scenes/gamescene.lua) a `g3d.newModel` on line 19 to create a "blockCursor". Is this the method to create the in-game blocks?
