### ISSUE TITLE
Geometry gets broken when is drawn to a canvas

### ISSUE THREAD

**Issue by fantasmashy** [groverburger/g3d#40]
![image](https://user-images.githubusercontent.com/49044996/223553907-0915aeac-f688-463c-b097-7b2fd9f9122a.png)
this is a cube

in love 11.3
chromebook (debian 11)

**Comment by shviller** [comment]
@fantasmashy: [This](https://love2d.org/wiki/love.graphics.setCanvas) is probably relevant:
> When using a stencil or [depth testing](https://love2d.org/wiki/love.graphics.setDepthMode) with an active Canvas, the stencil buffer or depth buffer must be explicitly enabled in setCanvas via the variants below.

**Comment by groverburger** [comment]
Let me know if this can fix the issue: https://github.com/groverburger/g3d/wiki/Can%27t-render-models-to-canvas

If not, it's probably an issue with g3d.

**Comment by groverburger** [comment]
> oh yes, it was the deph

Glad we could help! Closing this issue.
