### ISSUE TITLE
Rules for texture mapping?

### ISSUE THREAD

**Issue by gustavostuff** [groverburger/g3d#43]
I created this cube in Blender and texture mapping seems to be ok there, but it acts wierd once I import it on g3d.

![](https://i.postimg.cc/SsGv1Ph7/blender.png )

This is how it looks when I use the exported `obj` file along with that same texture:

![](https://i.postimg.cc/QM3SLqS6/face-1.png)

![](https://i.postimg.cc/pdJCPn6P/face-2.png)

another look from inside the cube:

![](https://i.postimg.cc/wvcvBDKT/cube-inside.gif)

For g3d I modified the texture just to show you the actual mapping done by g3d:

![](https://i.postimg.cc/MZN72Dpy/clear-wood-texture.png)

Thanks in advance!

**Comment by Tekkitslime** [comment]
I don't know why exactly, but it assumes texture origin to be bottom-left, when it should be intuitively top-left. The `g3d.loadObj` function supports flipping U and V texture coordinates, in this case you should call `g3d.loadObj` with the path of the .obj file, false and true to get the correct texture coordinates, and then pass it to `g3d.newModel` as the first argument. =)
